name: Bump Rust 🦀 crate version

on:
  workflow_dispatch:
    inputs:
      dist-location:
        description: 'Distribution location'
        type: choice
        options:
          - cln-plugin
          - cln-rpc
          - cln-grpc
        default: 'cln-rpc'
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install cargo release
      run: |
        cargo binstall cargo-release
        cargo binstall cargo-semver-checks

    - name: Determine version
      id: determine-version
      run: |
        if cargo semver-checks -p ${{ github.event.inputs.dist-location }} --release-type patch; then
          echo "bump=patch" >> $GITHUB_OUTPUT
        elif cargo semver-checks -p ${{ github.event.inputs.dist-location }} --release-type minor; then
          echo "bump=minor" >> $GITHUB_OUTPUT
        elif cargo semver-checks -p ${{ github.event.inputs.dist-location }} --release-type major; then
          echo "bump=major" >> $GITHUB_OUTPUT
        else
          echo "bump=unknown" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Bump version
      run: |
        cargo release version -p ${{ github.event.inputs.dist-location }} ${{ steps.determine-version.outputs.bump }} --execute --no-confirm

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "${{ github.event.inputs.dist-location }}: Bump the ${{ steps.determine-version.outputs.bump }} version"
        title: "${{ github.event.inputs.dist-location }}: Bump the ${{ steps.determine-version.outputs.bump }} version"
        body: |
          Triggered manually with option: ${{ github.event.inputs.dist-location }}
        branch: "${{ github.event.inputs.dist-location }}-version-bump"
        base: master
        labels: version-bump, automated
        delete-branch: true
